# Generated by Django 6.0.3 on 2026-04-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
