# Generated by Django 6.0.3 on 2026-04-16 20:32

import django.db.models.deletion
import pms_api.core.models.mixins
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lookups', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('fiscal_year', models.CharField(max_length=10)),
                ('justification', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('forwarded', 'Forwarded'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision_requested', 'Revision Requested')], db_index=True, default='draft', max_length=30)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('current_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_budget_requests', to='lookups.department')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget_request', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=(pms_api.core.models.mixins.SignalMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BudgetForwardingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('action', models.CharField(choices=[('forwarded', 'Forwarded'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned')], max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('step_number', models.PositiveSmallIntegerField()),
                ('acted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forwarding_actions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('from_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forwarded_from_steps', to='lookups.department')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('to_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forwarded_to_steps', to='lookups.department')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('budget_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forwarding_steps', to='budget.budgetrequest')),
            ],
            bases=(pms_api.core.models.mixins.SignalMixin, models.Model),
        ),
    ]
