# Generated by Django 6.0.3 on 2026-05-14 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetrequest',
            options={'ordering': ['-created_at'], 'permissions': [('submit_budgetrequest', 'Can submit a budget request for review'), ('forward_budgetrequest', 'Can forward a budget request to another department'), ('approve_budgetrequest', 'Can approve, reject, or return a budget request for revision')]},
        ),
    ]
