# Generated by Django 6.0.3 on 2026-05-14 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractor',
            options={'permissions': [('blacklist_contractor', 'Can blacklist or unblacklist a contractor')]},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'permissions': [('approve_payment', 'Can approve a contractor payment')]},
        ),
    ]
