# Generated by Django 6.0.3 on 2026-05-14 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'permissions': [('monitor_project', 'Can record monitoring status updates on a project')]},
        ),
    ]
