# Generated by Django 6.0.3 on 2026-04-27 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_created_by_user_deleted_at_user_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('manage_user', 'Can manage user accounts (activate, deactivate, reset password, assign groups)')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
