# Generated by Django 6.0.3 on 2026-05-14 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('manage_user', 'Can manage user accounts (activate, deactivate, reset password, assign groups)'), ('manage_superuser', 'Can operate on superuser accounts (deactivate/delete superusers)'), ('view_deleted_records', 'Can view soft-deleted records via ?include_deleted=true'), ('bypass_row_security', 'Can view records outside their department/ownership scope'), ('restore_records', 'Can restore soft-deleted records'), ('hard_delete_records', 'Can permanently delete records (bypass soft-delete)')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
