#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


exec celery \
    -A config \
    -b "${CELERY_BROKER_URL}" \
    flower \
    --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"
