#!/bin/bash

set -o errexit
set -o nounset


rm -f './celerybeat.pid'
exec watchfiles --filter python celery.__main__.main --args '-A config beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler'
